src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.recommended.cs
- closes #12
- Bugfix
CommunityToolkit or Reactive packages can be added to the project without a ViewModel/Model
These now require that Extensions Navigation be enabled as well.
=> Mvvm or Mvux should only be added with Extensions Navigation

build/.azure-pipelines.TemplateValidation.yml, build/templates/package-validation.yml, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Server/MyExtensionsApp.1.Server.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/GlobalUsings.cs
- closes #22
- Bugfix
Using the following:
```bash
dotnet new unoapp -n Issue22 -preset blank -tfm net7.0 -platforms android -platforms ios -platforms maccatalyst -platforms macos -platforms windows -platforms wasm -platforms gtk -platforms wpf -platforms linux-fb -presentation mvvm -server false -tests "" -vscode false -pwa false -di true -nav regions -log none -theme material
msbuild ./Issue22.sln
```
This will fail with a build error because the Uno.Extensions namespace is not included in the global namespaces.
Removes invalid conditions for additive process. Replaces `useRecommendedAppTemplate` condition
- and uses `useDependencyInjection` for the Uno.Extensions namespace
- and uses `useDataContracts` for the …
=> Fix Build Error for additive template

src/Uno.Templates/content/unoapp/Directory.Build.props
- closes #26 
- Bugfix
NoWarn includes Uno0001
Uno0001 is removed from the NoWarn overrides
=> Remove nowarn for Uno0001

.github/labeler.yml
- n/a
- Project Automation
there is no labeler.yml in the .github directory
there is now a labeler.yml defined
=> Fix run issue with the labeler

src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/Android/Resources/values/Styles.xml
Bugfix
Removes image at bottom of splash screen
=> fix: Duplicate logos

src/Uno.Templates/content/unoapp/Directory.Build.props, src/Uno.Templates/content/unoapp/Directory.Build.targets, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.UITests/GlobalUsings.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/GlobalUsings.cs
GitHub Issue (If applicable): closes #34
Setting `ImplicitUsings` to `enable` or `true` brings more namespaces than we need, e.g:
https://github.com/xamarin/xamarin-android/blob/3f756cc5ed7154f6384a53da62d60d77e0dd9e3d/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props#L19-L23 for Android, and https://github.com/xamarin/xamarin-macios/blob/1fd05057ed96083fc70ba0f0afb8bb544592ad3b/dotnet/Makefile#L143 https://github.com/xamarin/xamarin-macios/blob/1fd05057ed96083fc70ba0f0afb8bb544592ad3b/dotnet/Makefile#L17-L20 for ios/macos.
The platform-specific usings are now removed to avoid conflicts. From example, Android.Widget.Button conflicts with Microsoft.UI.Xaml.Controls.Button.
So now, we only include non-platform-specific …
=> fix: Remove platform-specific implicit usings

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.UITests/MyExtensionsApp.1.UITests.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.UITests/TestBase.cs
- closes #28 
- Refactoring
UI Test project targets net48
UI Test project will target which ever version of .NET that the solution is created with using the new UI Test Helpers which provides support for net6+
=> feat: UI Test net6+ support

src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Gtk/MyExtensionsApp.1.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Gtk/app.manifest, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.WPF/MyExtensionsApp.1.Skia.WPF.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.WPF/app.manifest, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj
- Bugfix
app.manifest is not properly used, which means the app don't adhere to DPI scaling changes (and fractional scaling)
- Add `<ApplicationManifest>` to all Windows targets
- Update `app.manifest` as per latest WinUI project template
=> fix: Add app.manifest to Windows targets

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/SecondPage.xaml
[Template] Provide Back Navigation when not using Toolkit https://github.com/unoplatform/uno.templates/issues/5
GitHub Issue (If applicable): closes #5 
- Feature
When we are not using the  using Uno.Toolkit.UI we can not use the to utu:NavigationBar.
So we do not have the some back options on the Second Page.
Now we have add the option to back on the second page.
- [] Tested code with current [supported SDKs](../README.md#supported)
#5
=> Provide Back Navigation when not using Toolkit

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/GlobalUsings.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainModel.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainViewModel.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Caching/IWeatherCache.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Caching/WeatherCache.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Endpoints/IApiClient.cs
closes: #3 
There are files that use local using.
Now the usings are located in the global.
https://github.com/unoplatform/uno.templates/issues/3
=> Add Mvvm/Mvux namespaces in GlobalUsings if selected

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/Shell.xaml, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/Shell.xaml.cs
GitHub Issue (If applicable): #60
- Bugfix
Splashscreen background is always white, even when browser set to dark theme (ie no theme background color set)
Uses the themed background brush
=> fix: Setting background of shell

src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj
- Bugfix
Only enable https://github.com/xamarin/xamarin-macios/issues/14812 workaround in Release configuratio as it may crash the debugger when enabled.
=> fix: Move exceptions workaround to release only as it breaks debugging

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.DataContracts/WeatherForecast.cs
- Bugfix
A couple of places where template is still using blank or recommende conditions outside of evaluators
blank/recommended preset only used in default evaluators
(needs https://github.com/unoplatform/uno.templates/pull/85 to be closed to pick up on cases used for test projects)
=> fix: Remove blank/recommended conditions

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.UITests/Given_MainPage.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MainPage.xaml
GitHub Issue (If applicable): closes #83
- Bugfix
No test projects created when using blank preset and specifying tests=ui|unit
Test projects are created
=> fix: Enabling unit and uitests for blank preset

src/Uno.Templates/content/unoapp/Directory.Build.targets
- n/a
- Other: Adds note to targets to indicate why we are removing global usings
=> chore: add note on why we remove the usings

build/.azure-pipelines.TemplateValidation.yml, src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/Android/MainActivity.Android.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/Android/MsalActivity.Android.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MacCatalyst/Info.plist, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/iOS/Info.plist, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/macOS/Info.plist, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Gtk/MyExtensionsApp._1.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Linux.FrameBuffer/MyExtensionsApp._1.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.WPF/MyExtensionsApp._1.Skia.WPF.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Wasm/MyExtensionsApp._1.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/MyExtensionsApp._1.Windows.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/Package.appxmanifest, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.recommended.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/appsettings.development.json, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/appsettings.json
GitHub Issue (If applicable): closes #50, closes #48 
- Feature
No support for oidc and msal
Adds oidc and msal to template
=> feat: Adding Oidc and Msal to template

src/Uno.Templates/content/unoapp/Directory.Build.props
This default setting is just plain evil. When you start a new project, you're bound to have unused fields, a few null annotation issues etc as you get started. `TreatWarningsAsErrors` considerable reduces developer productivity and slows down the inner dev-loop.
I'm not saying it is a bad setting to have at some point, but it's almost never the right setting to have when you're starting up on a new project - and even then you might only set it in release builds or CI builds to keep the dev-loop fast.
I'm suggesting you remove this setting from the starter template. It's even hidden in a global directory.build.props file so it wasn't even immediately obvious why all these build errors kept happening.
I almost never get to run my app because I'm …
=> Don't be evil: WarningsAsErrors sets people up for failure from the beginning

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/iOS/Info.plist
- Bugfix
Storyboard referenced that doesn't exist
Should use Resizetizer generated storyboard
=> fix: Remove launch storyboard name

src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/MyExtensionsApp._1.Windows.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
GitHub Issue (If applicable): closes #102
- Feature
VS complains if you try to run the Windows target without previously building it
VS already knows about running the MSIX, so no error on first run
=> fix: Correct windows tooling options

src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
- closes #72
- Refactoring
We provide a commented out block with a FrameworkReference Update should a developer encounter an error due to the version of the WinAppSdk that a dependency was built against create the need to specify it.
This has been replaced by the updated WindowsSdkPackageVersion property. This is also commented out and we are maintaining the same code comment block to indicate when developers may need it.
https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/5.0/override-windows-sdk-package-version#previous-behavior
=> chore: update from deprecated FrameworkReference Update

build/.azure-pipelines.TemplateValidation.yml, src/Uno.Templates/content/unoapp/.template.config/template.json
- closes #88
- Bugfix
When passing `-tests ''` with the recommended preset the ui and unit test projects are still created
We are adding an explicit none option so that the fallback does not get confused by an empty string.
`-tests none` to disable tests
=> Opt out of tests with Recommended preset

src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.blank.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.recommended.cs
- closes #120
- Refactoring 
The visibility of the `_window` property is inconsistent depending on whether you are creating a blank or recommended app.
The visibility is normalized as public with a private setter and the property has been renamed to be consistent with coding standard for a public property.
=> Rename Window as public property

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.DataContracts/MyExtensionsApp._1.DataContracts.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.DataContracts/Serialization/WeatherForecastContext.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Server/Apis/WeatherForecastApi.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Server/MyExtensionsApp._1.Server.csproj
- closes #38 
- Refactoring
We disable CS1591 in the DataContracts and Server so that we do not annoy developers who are not adding XML docs to everything while enabling full swagger docs from the generated template
Making the minimal API extensions internal to avoid issues with requiring XML docs, and adding a comment to the Serialization Context in the DataContracts. The NoWarn has been removed from both projects.
=> Remove nowarn for xml comments

src/Uno.Templates/content/unoapp/Directory.Build.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/12281
- n/a
- Refactoring
The Runtime Identifier is set at the Directory.Build.props if not set, which will affect the common library as well
We now only set this on the Mobile head.
=> Move runtime identifier to the Mobile head only

src/Uno.Templates/content/unoapp/Directory.Build.props
- closes #126 
- Refactoring
We add the value for SynthizeLinks in the Directory.Build.props which was necessary for the Shared Projects which we no longer use.
Because the property is no longer needed we are removing it from the Directory.Build.props
verified ok to remove with @jeromelaban
=> Remove unnecessary property

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/AppHead.xaml.cs, src/Uno.Templates/reinstall.ps1
GitHub Issue (If applicable): closes unoplatform/uno.resizetizer#129
- Bugfix
Icon not set for WinUI
Icon set
=> fix: Icon not set on WinUI window

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Wasm/MyExtensionsApp._1.Wasm.csproj
- closes #132 
- Bugfix
No webapp base path is set
The webapp base path is set
=> Adding webappbasepath

src/Uno.Templates/content/unoapp/.template.config/template.json
- #136 
- Bugfix
When creating a blank template CommunityToolkit.Mvvm is not added even when it is specifically specified as an argument
When creating a blank template neither CommunityToolkit.Mvvm or Uno.Extensions.Reactive will be automatically added. You can now specify `mvvm` to get CommunityToolkit.Mvvm with the blank preset. You can also now specify `none` from the recommended preset if you do not have Extensions Navigation enabled. If you do have Extensions Navigation then it will default back to Mvvm.
=> Cannot add mvvm with blank template

src/Uno.Templates/content/unoapp/.template.config/template.json
GitHub Issue (If applicable): closes #143 
- Bugfix
Fails to add Windows project to the generated solution in Windows because the Windows csproj isn't listed as an output. This is because the OS value is returning Windows_NT when run inside Visual Studio instead of just Windows
Checks for windows and windows_nt
=> fix: Change OS to look for both windows and windows_nt

build/.azure-pipelines.yml
- closes #150 
- Bugfix
Package is published all lowercase
Package will be generated with the correct casing
=> Fix generated package name

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/Directory.Build.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.sln, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj, src/Uno.Templates/content/unoapp/solution-config.props.sample, src/Uno.Templates/reinstall.ps1
- Replaces #141
- Feature
The projects core "shared" project and the mobile project will multi-target as necessary.
Developers may now optionally uncomment an import line in the Directory.Build.props and rename the sample file to single target. This is an opt in feature. We additionally have added the official VisualStudio .gitignore with the addition of a line to ignore the solution-config.props so that if a developer chooses to use this they will not accidently check the file into source control.
It will be up to the developer to create any solution filters that they may want. The linked docs explain this process in more detail.
=> Enable single target builds

src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/MyExtensionsApp._1.Windows.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
- Bugfix
Building windows target often resulted in build error: https://github.com/microsoft/WindowsAppSDK/issues/3554
This type of build error has been resolved in latest winappsdk
=> fix: WinAppSdk version bump to fix "PrecompiledHeaderFile" error when building Windows target

build/templates/canary-updater.yml, build/templates/package-validation.yml, src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Gtk/Program.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/GlobalUsings.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Services/Endpoints/IApiClient.cs, src/Uno.Templates/reinstall.ps1
GitHub Issue (If applicable): closes: #160, fixes: #162
- Bugfix
Missing http.winui reference
Warnings when building for android (see #162)
Http.winui is referenced
No warnings building for android
Global usings for uno.extensions have been removed
- [N/A] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [N/A] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [N/A] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) …
=> fix: Reference Http.WinUI from template

src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
- Bugfix
Only Assets/** are included as content
All images (ie **/*.png;**/*.bmp;**/*.jpg;**/*.dds;**/*.tif;**/*.tga;**/*.gif) are included as Content which matches the winappsdk behaviour
- [N/A] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [N/A ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ N/A] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR …
=> fix: Align image includes with win app sdk

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/reinstall.ps1
- Bugfix
The current version do not work for Markp
Now the new version works for Markup, but still disabled.
=> Update uno versions

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Gtk/MyExtensionsApp._1.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Linux.FrameBuffer/MyExtensionsApp._1.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.WPF/MyExtensionsApp._1.Skia.WPF.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Wasm/MyExtensionsApp._1.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/MyExtensionsApp._1.Windows.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
- Bugfix
Template references deprecated uno.extensions.toolkit package
Deprecated reference removed
=> fix: Removing deprecated Uno.Extensions.Toolkit package

build/templates/canary-updater.yml, build/templates/propertiesToUpdate.json, src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Gtk/MyExtensionsApp._1.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Linux.FrameBuffer/MyExtensionsApp._1.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.WPF/MyExtensionsApp._1.Skia.WPF.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Wasm/MyExtensionsApp._1.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/MyExtensionsApp._1.Windows.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
- Feature
Only Uno.Extensions and Uno.WinUI versions are in the uno.templates.csproj file. This will prevent other packages from being updated by the canary updater
The other Uno packages and Skia have been added to the csproj file
=> feat: Extracting package versions to csproj so updater will work

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp._1-vsmac.slnf, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/MyExtensionsApp._1.Base.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.sln
GitHub Issue (If applicable): 
- closes #176
- Feature
The base.props, app icon and splash screen resources are inaccessible while working in Visual Studio
A new csproj has been added to the solution that allows you to view these previously inaccessible files while still in Visual Studio. The solution uses the NoTargets SDK, is not referenced anywhere other than the Solution and does not affect the build at all.
NOTE: The AppHead.xaml/AppHead.xaml.cs are hidden from this project as they should be modified from the existing platform head projects where they are already linked in by the base.props
=> Show the base.props and icon files

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/MyExtensionsApp._1.Base.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/base.props
GitHub Issue (If applicable): closes #198
- Refactoring
Image Assets are only displayed in the Base project
Icon and Splash Screen assets are now added as linked files with the base.props. Note that LinkBase and wildcards were not working to link the files in for Visual Studio. As a result each file is explicitly added.
=> Link image assets to head projects

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/base.props
- closes #175
The splash screen has a blue background
The splash screen has a white background
=> Update background color for the splash screen

build/templates/dotnet-install-windows.yml, src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Gtk/MyExtensionsApp._1.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Linux.FrameBuffer/MyExtensionsApp._1.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.WPF/MyExtensionsApp._1.Skia.WPF.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Tests/MyExtensionsApp._1.Tests.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.UITests/MyExtensionsApp._1.UITests.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Wasm/MyExtensionsApp._1.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/MyExtensionsApp._1.Windows.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
- Bugfix
Canaries break due to mismatch of versions for Microsoft.Identity.Client library
Updated version of library used by template and removed unnecessary references in head projects
- [N/A] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [N/A] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [N/A] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [N/A] Associated with an issue (GitHub or internal)
Internal Issue (If …
=> fix: Canary builds

src/Uno.Templates/content/unoapp/Directory.Build.props, src/Uno.Templates/reinstall.ps1
GitHub Issue (If applicable): closes [#183](https://github.com/unoplatform/uno.templates/issues/183)
- Bugfix
Build errors related to RuntimeIdentifiers with .Net8 on shared project
all platform now builds and run
=> fix net8 build errors on windows

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.UITests/Constants.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.UITests/TestBase.cs
GitHub Issue (If applicable): closes #215
- Bugfix
See #215 
Updates UITest to latest dev release which fixes the chromedriver download behavior
It also adds support for running UITests in Edge
- [N/A] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [N/A] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
=> fix: Updating UITest version

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.MauiControls/AppBuilderExtensions.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.MauiControls/Styles.xaml, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.MauiControls/Styles.xaml.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.blank.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.recommended.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj, src/Uno.Templates/reinstall.ps1
- implements unoplatform/uno.extensions#1749
- Feature
There is no ability to provide Maui styles globally for the application which would normally go in the Maui Application.
We now use the new extension for Maui Embedding to provide a Resource Dictionary that will be provided in the parent resources so that styles are automatically applied and resources are available.
=> chore: move Maui registrations into MauiControls lib

src/Uno.Templates/content/unoapp/solution-config.props.sample
- Bugfix
When specifying the OverrideTargetFrameworks in the sample-config.props, if you uncomment multiple lines, only the last framework is included
As many lines as necessary can be uncommented and the tfms are cumulative
=> chore: Revert removal of OverrideTargetFrameworks

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.MauiControls/EmbeddedControl.xaml
- Bugfix
maui controls don't render to fill available space when added to embedded control
EmbeddedControl fills to available space in the Uno app. Then Maui control will render correctly based on their horizontal/vertical alignment options.
=> fix: Force embedded control to expand to fill available space

src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
- Bugfix
Adding a ProgressRing to a blank application will display an error on all targets except Windows as it needs uno.winui.lottie reference
Adds Uno.WinUi.Lottie to non-winui targets
=> fix: Adding reference to Uno.WinUI.Lottie

src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
https://github.com/unoplatform/uno.templates/pull/231 - leaves uno.winui.lottie package reference in separate block when not referencing winappsdk
Package reference is with all the other package reference when not targetting winappsdk
=> chore: Tidyup

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.MauiControls/App.xaml, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.MauiControls/EmbeddedControl.xaml, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.MauiControls/UnoImageConverter.cs
- Bugfix
Image isn't displaying on android
Template includes a converter that adjusts the path to the image for Android
=> feat: Adding image converter to template

src/Uno.Templates/content/unoapp/.vscode/launch.json, src/Uno.Templates/content/unoapp/.vscode/tasks.json
- Bugfix
- Feature
Launch.json and Task.json contains mobible, wasm and gtk entries, even if those platforms aren't selected
Launch.json has mobile target last, meaning that web debugging is selected by default
Launch.json now has mobile target first - makes it easier for developers migrating from vs mac
Launch.json and Task.json items are conditional based on targets selected
=> feat: Improving VSCode debugging experience

src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/LoginModel.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/LoginViewModel.cs
GitHub Issue (If applicable): closes #https://github.com/unoplatform/uno.templates/issues/209
- Bugfix
Dispatcher not passed into the LoginAsync method - throws exception and fails login
Dipatcher passed into LoginAsync method
=> fix: Adding dispatcher to LoginAsync calls

src/Uno.Templates/content/unoapp/.vsconfig
- closes #227
- Bugfix
all recommended VS components are added to the generated project's .vsconfig
this is now trimmed down based on the platforms selected
=> Limit required VS components based on project selections

build/templates/dotnet-install-windows.yml, build/templates/package-validation.yml
- Bugfix
Build broken because of MS update
Build fixed by pinning dotnet workload restore
=> fix: Pinning workload restore

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.MauiControls/EmbeddedControl.xaml
Just a quick fix to remove the xmlns for CommunityToolkit.Maui from our template
=> fix: removed toolkit xlmns

src/Uno.Templates/content/unoapp/.template.config/template.json
- closes #290
- Bugfix
The server project is created by default
The server project is created by default for the recommended preset and excluded by default for blank preset.
=> Only provide the server project by default in recommended preset

.editorconfig, src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.MauiControls/MyExtensionsApp._1.MauiControls.csproj, src/Uno.Templates/content/unomauilib/.template.config/dotnetcli.host.json, src/Uno.Templates/content/unomauilib/.template.config/ide.host.json, src/Uno.Templates/content/unomauilib/.template.config/template.json
- closes #293 
- Feature
You can only get a MAUI Class library for MAUI Embedding as part of the unoapp template
You can now create a stand alone MAUI Class library for MAUI Embedding without any additional projects. This will make it easier to add to existing projects.
=> Adding stand alone Maui Embedding class lib

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Server/Program.cs
- closes #299
- Bugfix
The JsonSerializationContext is added to the JsonSerializerOptions with the AddContext method.
The JsonSerializationContext is added to the JsonSerializationOptions with a JsonTypeInfoResolver using the TypeInfoResolver property. This is the new recommended way from the net8.0 release notes.
https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#chain-source-generators
**NOTE**: Do not backport. The TypeInfoResolver property was introduced in net7.0 and is not available for net6.0.
=> Remove use of deprecated API

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/AppHead.xaml.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Gtk/MyExtensionsApp._1.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Linux.FrameBuffer/MyExtensionsApp._1.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.WPF/MyExtensionsApp._1.Skia.WPF.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Wasm/MyExtensionsApp._1.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.recommended.cs, src/Uno.Templates/reinstall.ps1
- closes #289 
Head projects target Uno.WinUI.RemoteControl
Package reference updated to use new Uno.WinUI.DevServer package for Hot Reload. All heads have been updated as well so that they consistently only include the reference for Debug builds. This was missed for some heads when using CPM.
=> chore: update to use new DevServer package

src/Uno.Templates/content/unoapp/.template.config/dotnetcli.host.json, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
- closes #319 
- Feature
DSP is enabled by default when Material is enabled
DSP is now a separate flag and is disabled by default for the blank preset and enabled by default for the recommended preset.
=> Making DSP an optional feature

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unomauilib/.template.config/template.json
GitHub Issue (If applicable): closes #325
- Bugfix
ios then android in tfms list
android then ios in tfms list
=> fix: Prioritize android before ios

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MainPage.xaml
GitHub Issue (If applicable): closes #328
- Bugfix
Material namespace not included
SafeArea not applied to MainPage in blank template
Material namespace is being include
SafeArea is applied to StackPanel inside MainPage
SafeArea changed to use VisibleBounds, not All (since SoftInput value (included in All) doesn't make sense on root element)
=> fix: Correct Material namespace and safearea

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MainPage.xaml
- n/a follow up for #324 
- Bugfix
Inserted XAML Namespaces use tabs
Inserted XAML Namespaces use the same spacing that already exist in the XAML files.
=> Use spaces for new xaml namespaces

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/Properties/PublishProfiles/win-arm64.pubxml, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/Properties/PublishProfiles/win-x64.pubxml, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/Properties/PublishProfiles/win-x86.pubxml
- Bugfix
Hot Reload window reports:
13:27 29.12 HRWindowsApp.Windows: [Warning] Hot Reload is not available because startup hooks have been disabled, possibly due to trimming.
This will prevent HR working due to trimming being enabled in debug
Trimming is only enabled in release builds
=> fix: Enabling XAML hot reload in debug by avoiding trimming

src/Uno.Templates/content/unoapp/.template.config/template.json
GitHub Issue (If applicable): closes #271 
- Bugfix
Warning when unable to bind to OS (typically on Mac)
Default value specified for when OS value isn't available
=> fix: Setting default value for OS binding

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/Icons/icon.svg, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/Icons/icon_foreground.svg, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/Splash/splash_screen.svg, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/base.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/Android/Main.Android.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MacCatalyst/Info.plist, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/iOS/Info.plist, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/macOS/Info.plist
GitHub Issue (If applicable): closes #342
- Feature
Name of icon files isn't clear what they're for
Icon file is now just icon.svg
Icon foreground is called icon_foreground.svg
=> feat: Updating name of icon files

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj, src/Uno.Templates/reinstall.ps1
GitHub Issue (If applicable): closes #354
- Bugfix
Generated resw being incorrectly included in build
Prevent generated resw files from being added to build
=> fix: Intermittent build error

src/Uno.Templates/content/unoapp/.vscode/launch.json, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Server/Properties/launchSettings.json, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.UITests/Constants.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Wasm/Properties/launchSettings.json
- Bugfix
This is a workaround for https://developercommunity.visualstudio.com/t/BrowserLink-WebSocket-is-disconnecting-a/10500228, which can break the hot reload session when the port is specifically 5000 in some machine configurations.
=> fix: Adjust launchSettings.json to use a port other than 5000

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/Properties/launchsettings.json, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.blank.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.recommended.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/GlobalUsings.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MainPage.xaml, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/MainPage.xaml, src/Uno.Templates/reinstall.ps1
- Feature
Adds packages and code to enable Hot Reload
=> feat: Enable HotReload

src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
- n/a
- Other... Enable Generator by default
If you use C# Markup and want extensions generated for your custom controls you need to additionally install the Generator package
The Generator is now added by default to provide extensions automatically for your custom controls.
=> chore: adding Generator to generate for local types

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Tests/MyExtensionsApp._1.Tests.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.UITests/MyExtensionsApp._1.UITests.csproj
- Bugfix
Executing "dotnet test --no-build" triggers the following error indicating missing IsTestProject property
dotnet test will detect the test project
=> chore: Adding IsTestProject so that dotnet test executes tests

src/Uno.Templates/content/unoapp/Directory.Build.props
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.templates/issues/376
- Bugfix
Multiple warnings for CA1416 despite supported platform os version being set
No CA1416 warnings in debug 
=> fix: Disable CA1416 when in debug

src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/LoginPage.xaml.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/MainPage.xaml.cs
- n/a
- Bugfix
CSM version of the template still using strongly typed `RowDefinitions` that were required in 4.x
CSM now uses implicit type from the Grid
=> Update CSM for Uno 5 remove strong typing on Grid Row Definitions

src/Uno.Templates/content/unoapp/Directory.Build.props
- Bugfix
Applies solution load workaround to avoid having VS asking to reload projects when creating a template from the VSIX. VS 2022 only.
=> fix: Avoid VS 2022 from asking to reload the mobile project

src/Uno.Templates/content/unoapp/Directory.Build.props
- Bugfix
Adjust workaround for hotreload for https://github.com/dotnet/sdk/issues/36666.
=> fix: Disable commit generation in net8 for HR

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/Directory.Build.props, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.DataContracts/MyExtensionsApp._1.DataContracts.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.MauiControls/MyExtensionsApp._1.MauiControls.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Server/MyExtensionsApp._1.Server.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Shared/MyExtensionsApp._1.Shared.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Gtk/MyExtensionsApp._1.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Linux.FrameBuffer/MyExtensionsApp._1.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.WPF/MyExtensionsApp._1.Skia.WPF.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Tests/MyExtensionsApp._1.Tests.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.UITests/MyExtensionsApp._1.UITests.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Wasm/MyExtensionsApp._1.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/MyExtensionsApp._1.Windows.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
- n/a
- Feature
If you create the app with net7 and want to experiment with net8 you need to find/replace net7 with net8 in all of the projects.
You can now simply change the `DotNetVersion` in the Directory.Build.props. This will globally update the entire solution to use the version that you want. 
**NOTE:** This may result in undesired behavior such as with MAUI Embedding where get the requirement for the additional NuGet Packages, and you may have API breaks in libraries you are referencing when changing from net7 to net8 to net9.
=> Control .NET version globally from Directory.Build.props

build/.azure-pipelines.TemplateValidation.yml, build/templates/package-validation.yml, src/Uno.Templates/content/unoapp/.template.config/template.json
- closes #417 
- Feature
.net7.0 is the default Target Framework
.net8.0 is the new default target framework
Also adjusts Maui Embedding to use a calculated parameter in the template.
=> Make net8.0 default

build/.azure-pipelines.TemplateValidation.yml, src/Uno.Templates/content/unoapp/.template.config/template.json
- n/a
`dotnet new unoapp` results in the creation of an app with the recommended preset
`dotnet new unoapp` results in the creation of an app with the blank preset
=> Make the blank preset the default choice

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/AzurePipelines/jobs/unit-test.yml, src/Uno.Templates/content/unoapp/Directory.Build.props, src/Uno.Templates/content/unoapp/Directory.Build.targets, src/Uno.Templates/content/unoapp/GitHub/workflows/ci.yml, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.MauiControls/MyExtensionsApp._1.MauiControls.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Gtk/MyExtensionsApp._1.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Linux.FrameBuffer/MyExtensionsApp._1.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.WPF/MyExtensionsApp._1.Skia.WPF.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Wasm/MyExtensionsApp._1.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/MyExtensionsApp._1.Windows.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj, src/Uno.Templates/content/unoapp/solution-config.props.sample, src/Uno.Templates/content/unomauilib/.template.config/template.json
GitHub Issue (If applicable): closes #424 #423 
- Bugfix
If you add non-mobile overrides, the mobile project won't build.
OverrideFrameworkVersions is now designed to be single target - if you uncomment more than one line in the solution-config.props it will pick up only the last
Validation messages have been added to build.props to help warn developers if they are trying to build a project with an invalid set of tfms/overrides
=> fix: Adjusting overrides to be single target and provide warnings

src/Uno.Templates/content/unoapp/.template.config/template.json
- fixes unoplatform/uno#14431
- Bugfix
The Symbol name is duplicated between parameter to disable DSP and the generated symbol that replaces the Generator Output Type in the csproj.
We renamed the generated symbol to avoid a name clash. `dspGenerator` and `DspGenerator` these seem to have been similar enough to potentially cause issues.
=> Avoid name clash for DSP Generator

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/AppResources.xaml, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Styles/MaterialFontsOverride.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Styles/MaterialFontsOverride.xaml
- n/a
Font Overrides use default Roboto Fonts that aren't actually needed anymore.
FontOverrides.xaml has been removed. We now show developers how to override in a commented out ResourceDictionary added directly to the FontOverrideDictionary property of the MaterialTheme or MaterialToolkitTheme
=> Remove MaterialFontsOverride.xaml

src/Uno.Templates/content/unoapp/.template.config/dotnetcli.host.json, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj
- closes #432 
- Feature
To use WASM Multi-Threading you must first know about it, have read the docs, and then modified your project with the additional properties that need to be set.
When creating a new project you can now optionally specify `-wasm-multi-threading` from the CLI to enable WASM Multi-Threading. This includes a comment in the csproj to the docs as this is still a new feature and Multi-Threading is still not fully supported by the dotnet team. Also for that reason it is disabled by default and must be opted into. We will look to change this behavior when the feature is considered stable by Microsoft.
=> Enable wasm multi-threading

src/Uno.Templates/content/unoapp/GitHub/workflows/ci.yml, src/Uno.Templates/content/unoapp/azure-pipelines.yml
- closes #433 
- related dotnet/templating#7269
- Bugfix (Workaround)
When someone creates a template without Unit Tests but with GitHub Actions, the generated YAML is malformed as the template engine removes most but not all of the code block for the Unit Test job.
We now have an empty `#else`. The Template Engine seems to now properly box the job for the Unit Tests and include it when the condition is true and exclude it in its entirety when the condition is false.
This is a workaround. Hopefully the .NET Templating team will come up with a better long term fix for this so we can remove the hack of the empty `#else`
=> Workaround for malformed YAML when tests are disabled

src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Shared/MyExtensionsApp.1.Shared.csproj
Fixes #463
GitHub Issue (If applicable): closes #463
- Bugfix
Invalid token left in code after running template
No invalid tokens remain
=> fix: The new "shared" project does not have `$libraryBaseTargetFramework$` replaced

src/Uno.Templates/content/unoapp/Directory.Build.props
- Bugfix
App displays the following warning:
warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win10-arm64, win10-x64, win10-x86. Affected libraries: Microsoft.WindowsAppSDK. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.
No WinAppSDK warning
=> fix: Adding UseRidGraph to remove warning

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/AppResources.xaml
- closes #468
- Bugfix
When using Material there was still an un-named xmlns on the Resources node itself. This caused the build to assume the children were within that namespace.
We only use the namespaces at the top of the AppResources.
=> Incorrect xmlns on Material Resources

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.MauiControls/EmbeddedControl.xaml, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.MauiControls/EmbeddedControl.xaml.cs
- closes #466
- Bugfix
If creating a blank app which defaults to use Frame Navigation and then selecting MVVM and Maui, the Maui Control will be wired up to expect that it should data bind to the ViewModel. Since we are using Frame Navigation there is no ViewModel available.
When selecting these options the CommunityToolkit.Mvvm package will still be install and no ViewModel will be created for the page, however the Maui Control will now recognize that we are using Frame Navigation and will default back to using the Clicked Event Handler in the Control's code behind to drive the updated text in the button and track the count state.
Also updating the computed symbol name to make it clearer that it is used …
=> Maui Control doesn't work with Frame Navigation

src/Uno.Templates/content/unoapp/.vscode/extensions.json
- Feature
Opening a new solution, based on the templates, inside VS Code does not suggest installing the Uno Platform extension. Instead it suggest installed C# DevKit which does not work with our extension.
This will suggest the installation of the Uno Platform extension (if not already installed) when opening the solution folder inside VS Code.
As the Uno Platform extension depends on the MS C# extension, the latter will also be installed (if not already). Sadly it does not enable the `useOmniSharp` setting even when C# DevKit is not present :( The **Uno Platform** logs prints an error and a link to the documentation in this case [1].
This also stop VS Code from recommending C# DevKit (which was done …
=> feat: Recommend unoplatform.vscode inside VS Code

src/Uno.Templates/content/unoapp/.vscode/extensions.json
Adapt VS Code extension recommendation to the new default.
* `unoplatform.vscode` is recommended
* `ms-dotnettools.csdevkit` was unwanted (for O# compatibility)
* `unoplatform.vscode` is recommended **and** has a dependency on `ms-dotnettools.csdevkit`
=> chore: remove unwanted recommendation on vscode extension

src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj
- Bugfix
VS Code with OmniSharp can load the solution create from the templates.
VS Code with C# DevKit can NOT load the solution create from the templates. In this case a notification is shown
> Failed to restore solution.
and the logs shows
```
Determining projects to restore...
/usr/local/share/dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: To build a project targeting Windows on this operating system, set the EnableWindowsTargeting property to true. [/Users/poupou/git/external/uno/Uno.Samples/reference/SimpleCalc/MVU-X-CSharp/SimpleCalculator.Windows/SimpleCalculator.Windows.csproj]
```
VS Code can load the solution in …
=> fix: allow vscode w/dev kit to load solutions made from template

src/Uno.Templates/content/unoapp/.vscode/launch.json
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.templates/issues/497
- Bugfix
Ensures that vscode will pre-build the app before starting the app's server, avoiding `about:blank` navigation issues.
=> fix: Use pre-launch task for vscode wasm

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/Directory.Build.props, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.MauiControls/MyExtensionsApp.1.MauiControls.csproj
- Feature
WinUI requires "UseRidGraph" to be set to true due to not supporting net8 runtime identifiers
WinAppSdk is updated to latest release
UseRidGraph property has been removed as no longer required
=> feat: Updating winappsdk version and removing UseRidGraph (as no longer required with 1.4.231219000)

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginPage.xaml.cs
Fixes #505
GitHub Issue (If applicable): closes #505 
- Bugfix
The custom login logic with C# markup has an incorrect variable, so compilation fails
The variable is binded correctly now
- [ X ] Associated with an issue (GitHub or internal)
https://github.com/unoplatform/uno.templates/issues/505
=> Fixing incorrect variable in custom login logic with C# markup

build/.azure-pipelines.TemplateValidation.yml, build/templates/dotnet-install-windows.yml, build/templates/package-validation.yml, build/templates/propertiesToUpdate.json, src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.MauiControls/MyExtensionsApp.1.MauiControls.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj, src/Uno.Templates/content/unomauilib/.template.config/template.json, src/Uno.Templates/reinstall.ps1
- n/a
Template provides an option for both .NET 7.0 and .NET 8.0
Template is dropping support for .NET 7.0 in favor of having the minimum target be the latest LTS version (.NET 8.0). Will add .NET 9.0 when a preview is available.
=> Drop net7 support

src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Wasm/UnoQuickStart.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj
This group was required when VSIX templates were used, we're using dotnet new templates now.
=> fix: Remove unused itemgroup

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/Directory.Build.props, src/Uno.Templates/content/unoapp/Directory.Build.targets, src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Shared/MyExtensionsApp.1.Shared.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Gtk/MyExtensionsApp.1.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Linux.FrameBuffer/MyExtensionsApp.1.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.WPF/MyExtensionsApp.1.Skia.WPF.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.sln, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/ReadMe.md, src/Uno.Templates/content/unoapp/global.json, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Skia.csproj, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Wasm.csproj, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.csproj, src/Uno.Templates/content/unolib-crossruntime/global.json, src/Uno.Templates/content/unolib/.template.config/dotnetcli.host.json, src/Uno.Templates/content/unolib/.template.config/template.json, src/Uno.Templates/content/unolib/CrossTargetedLibrary.csproj, src/Uno.Templates/content/unolib/global.json, src/Uno.Templates/reinstall.ps1
- closes #365
- Bugfix
- Feature
Projects use the Microsoft.NET.Sdk. The Mobile head lacks the necessary project capabilities which causes Visual Studio on Windows to want to reload the project.
Projects now use the Uno.Sdk. NuGet packages that ship as part of the Uno repo are now versioned with the $(UnoVersion) from the Uno.Sdk. A global.json has been added to provide an easier way to manage and the version of Uno globally across the solution.
=> Use Uno.Sdk

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/Directory.Build.targets
- closes #474
From the CLI you are able to create a project with a space in the Project Name
If you create a project with a space in the project name a target will be added to the Directory.Build.targets. This will create an error to let you know you've created a project with an invalid name and that you should recreate the project without the use of spaces in the name.
=> fix: adding intentional break for invalid project name

src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Shared/AppHead.xaml.cs
- closes #382
- Bugfix
The template includes an unused condition for NETFX_CORE which came from the legacy template but is not defined. 
As WinAppSdk already uses the Console Logger there is no reason to switch this to the Debug logger by default. As a result we are simply removing the `NETFX_CORE` condition with the Debug Logger
=> Remove unused Logging Condition

src/Uno.Templates/content/unoapp-uwp/.template.config/template.json
- fixes #511
- Bugfix
The source modifiers uses the lowercase `mobile` where the symbol used in the template uses the uppercase `Mobile`
The source modifier uses the correct `Mobile` for the symbol.
=> Exclude the Mobile project when Mobile is false

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj
- n/a
- Bugfix
We still have references to IsWinAppSdk which isn't defined soon enough in the Uno.Sdk
We are reverting to check the TargetFramework
=> Use TargetFramework instead of IsWinAppSdk

src/Uno.Templates/content/unoapp/.template.config/template.json
- n/a
- Bugfix
The Recommended preset uses the display name 'Default' even though the default preset has been changed to blank.
The Recommended display name now shows 'Recommended'
=> Fix preset display name for Recommended preset

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/Shell.xaml.cs
- n/a
- Bugfix
When using C# Markup the Shell uses the RowDefinitions extension that takes the actual GridLength's.
When using C# Markup the Shell uses the succinct syntax for RowDefinitions
=> Use succinct syntax for RowDefinitions

src/Uno.Templates/content/unoapp/.template.config/dotnetcli.host.json, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/nuget.config, src/Uno.Templates/content/unoapp/vs-workaround.config
- n/a
- Workaround
Visual Studio 17.8 gets upset when creating a project with a custom Sdk unless you have a nuget.config in the project.
We now have an option for the VSIX to specify an override property to provide the nuget.config when creating a project in 17.8.
=> Add VS 17.8 workaround

src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj, src/Uno.Templates/reinstall.ps1
- n/a
WASM must explicitly load both Microsoft.NET.Sdk.Web and Uno.Sdk
WASM now only needs to load the Uno.Sdk
requires: unoplatform/uno#15204
=> Cleanup WASM Sdk Loading

src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Server/MyExtensionsApp.1.Server.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Gtk/MyExtensionsApp.1.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Linux.FrameBuffer/MyExtensionsApp.1.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.WPF/MyExtensionsApp.1.Skia.WPF.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.blank.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.recommended.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj
- n/a
- Bugfix
Maui Embedding uses the EmbeddingApplication which is obsolete in the updated version of Uno.Extensions.
Maui Embedding now just uses the default Application class
=> Maui Embedding Fix

src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.csproj, src/Uno.Templates/content/unolib/CrossTargetedLibrary.csproj
- n/a
- Bugfix
Project includes items that WinAppSdk would include by default
This is removed as these items are included by default with the Uno.Sdk
=> Remove default sdk items

src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj
- fixes #487
A default RuntimeIdentifier is provided for iOS/MacOS/MacCatalyst
The Mobile head now aligns with the default behavior of a MAUI project by not providing a default.
=> Align with MAUI behavior no default RuntimeIdentifier

build/.azure-pipelines.CrossRuntimeValidation.yml, build/.azure-pipelines.UWPValidation.yml, build/.azure-pipelines.UnoLibValidation.yml, build/.azure-pipelines.UnoMauiLibValidation.yml, build/.azure-pipelines.yml, build/templates/template-validation.yml, src/Uno.Templates/Uno.Templates.csproj, src/Uno.Templates/content/unoapp-uwp/.template.config/template.json, src/Uno.Templates/content/unoapp-uwp/Directory.Build.props, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Shared/App.xaml.cs, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.UWP/UnoQuickStart.Uwp.csproj, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Wasm/UnoQuickStart.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.MauiControls/App.xaml, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.MauiControls/MyExtensionsApp.1.MauiControls.csproj, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/Directory.Build.props, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Skia.csproj, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Wasm.csproj, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.csproj, src/Uno.Templates/content/unomauilib/.template.config/template.json
- closes #559
- closes #553
- Bugfix
The Cross Runtime library for Wasm gets updated to use an Exe for the output type.
The Wasm head explicitly sets the Output Type as Library.
=> Fixing Cross Runtime template

src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj
- fixes unoplatform/uno#15500
- closes #568 
- Bugfix
There is a typo in the Mobile head for the validation task of the OverrideTargetFramework
The typo has been fixed
=> fix: typo in OverrideTargetFramework validation task

build/.azure-pipelines.TemplateValidation.yml, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj
- Fixes #572
- Bugfix
The template adds references for Lottie and DevServer with a condition for when the TargetFramework does not contain windows10... The template conditionally adds references when we do not have a windows head without the Condition which results in duplicate references.
We now wrap both sets of PackageReferences in template conditions so that only one of the 2 blocks is included in the output project.
=> Duplicate package reference

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/Directory.Packages.props, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Gtk/MyExtensionsApp.1.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Linux.FrameBuffer/MyExtensionsApp.1.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.WPF/MyExtensionsApp.1.Skia.WPF.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj
Reverts unoplatform/uno.templates#579, it will be fixed by https://github.com/unoplatform/uno/pull/15567 instead.
=> chore: Revert "Adding SkiaSharp packages"

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj
- n/a
- Bugfix
browserwasm is only the first tfm when not using Windows
browserwasm is now the first tfm
=> Fixing the TFM Order

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.blank.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/Desktop/Program.cs
Ensures that platform host logging shows up in the console for desktop
=> feat: Initialize logging earlier in desktop target

src/Uno.Templates/content/unoapp-uitest/UnoUITestsLibrary.csproj, src/Uno.Templates/content/unoapp-uwp/Directory.Build.props, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Mobile/UnoQuickStart.Mobile.csproj, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Skia.Linux.FrameBuffer/UnoQuickStart.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Skia.WPF/UnoQuickStart.Skia.WPF.csproj, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Wasm/UnoQuickStart.Wasm.csproj, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/Directory.Build.props, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.DataContracts/MyExtensionsApp.1.DataContracts.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.MauiControls/MyExtensionsApp.1.MauiControls.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Server/MyExtensionsApp.1.Server.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Tests/MyExtensionsApp.1.Tests.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.UITests/MyExtensionsApp.1.UITests.csproj, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/Directory.Build.props, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Skia.csproj, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Wasm.csproj, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.csproj, src/Uno.Templates/content/unolib/CrossTargetedLibrary.csproj, src/Uno.Templates/content/unomauilib/.template.config/template.json
This change restores the original netX.0 target framework in csproj, and removs the use of `$(DotnetVersion)`, given that most solutions will have only one project to start with.
It is done for few reasons:
- Familiarity with other non-uno projects, where projects are generally authored this way
- Smaller string to define targets
- Easier string lookup
- Less confusing `DotnetVersion` variable that users may not know where the definition is coming from
This change makes it a bit less easy to change the target framework for the whole solution, but it's a generally known process from developers that use find+replace to do so.
=> refactor: Restore original targetframework

build/.azure-pipelines.TemplateValidation.yml, build/templates/dotnet-install-windows.yml, build/templates/package-validation.yml, build/templates/template-validation.yml, src/Uno.Templates/content/unoapp-uitest/.template.config/dotnetcli.host.json, src/Uno.Templates/content/unoapp-uitest/.template.config/template.json, src/Uno.Templates/content/unoapp-uitest/UnoUITestsLibrary.csproj, src/Uno.Templates/content/unoapp-uwp/.template.config/dotnetcli.host.json, src/Uno.Templates/content/unoapp-uwp/.template.config/template.json, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Mobile/UnoQuickStart.Mobile.csproj, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Skia.Linux.FrameBuffer/UnoQuickStart.Skia.Linux.FrameBuffer.csproj, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Skia.WPF/UnoQuickStart.Skia.WPF.csproj, src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Wasm/UnoQuickStart.Wasm.csproj, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/AzurePipelines/steps/install-dependencies.yml, src/Uno.Templates/content/unolib-crossruntime/.template.config/dotnetcli.host.json, src/Uno.Templates/content/unolib-crossruntime/.template.config/template.json, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Skia.csproj, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Wasm.csproj, src/Uno.Templates/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.csproj, src/Uno.Templates/content/unolib/.template.config/dotnetcli.host.json, src/Uno.Templates/content/unolib/.template.config/template.json, src/Uno.Templates/content/unolib/CrossTargetedLibrary.csproj, src/Uno.Templates/content/unomauilib/.template.config/template.json
- closes #598 
- Feature
Templates other than the main unoapp template only support net8.0
All templates now have the same tfm property to allow users to create a project with net8 or net9
=> adding net9.0 support

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Properties/launchSettings.json
closes https://github.com/unoplatform/uno-private/issues/422
=> fix: Don't include windows profiles if WinAppSDK is not enabled

src/Uno.Templates/content/unolib/.template.config/dotnetcli.host.json, src/Uno.Templates/content/unolib/.template.config/template.json
- closes unoplatform/uno-private#424
- Feature
`global.json` is always included in the Library template
`global.json` is included by default, but there is a new template option that allows you to exclude the `global.json` so that you can easily add the library to an existing solution and use the `global.json` from your existing project.
=> Allow hiding the global json in the library template

src/Uno.Templates/content/unoapp/GitHub/steps/install_dependencies/action.yml
Bugfix
CI step "Run Uno.Check" contains a wrong parameter:
Error: Unknown command 'vswin'.
fixed parameter
=> fix: uno-check parameter 'vswin' to '--skip vswin'

src/Uno.Templates/content/unoapp/.template.config/template.json
- closes #636
- Bugfix
Images are missing
Images correctly show up
=> fix: missing image assets

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj
- Add missing conditional flags for UI Testing
- Bugfix
No updates occur to enable UI Testing
We now provide the additional flags in the template when UI Tests are also added.
=> Add missing properties for UI Testing

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj
- n/a
- Feature
Incorrect Feature added for ThemeService. No feature flags exist for SVG and Lottie
The Correct `ExtensionsCore` Feature is added for the ThemeService. SVG and Lottie have been added as options. `Lottie` is only added when using the default Fluent from WinUI/Uno.WinUI. Both Material and Cupertino themes have dependencies on Lottie.
=> SVG & Lottie Features

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.xaml
- closes #664
- Bugfix
Recommended preset includes xmlns for wasm
We no longer reference the unused xmlns for wasm in any version of the template
=> Remove unused xmlns for wasm

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MainPage.xaml, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainPage.xaml
- closes #649 
- Feature
Page content is in a Grid/StackPanel
Page content is wrapped in a ScrollViewer to ensure that if you rotate the screen on a phone the content will still remain viewable.
=> Adding ScrollViewer to ensure all content is viewable

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj
- n/a
ThemeService template option is tied to the ExtensionsCore UnoFeature
ThemeService template option is now tied to the ExtensionsCore alias ThemeService
=> Use ThemeService alias for ThemeService template option

.github/ISSUE_TEMPLATE/bug-report.yml
- Feature
Added Rider as an option for a Template Host in the Bug Report template because latest Rider 2024.1 EAP now supports CLI templates
=> Update bug-report.yml to include Rider in Template Host

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj, tools/TemplateTfmSwitchGenerator/.gitignore, tools/TemplateTfmSwitchGenerator/Platform.cs, tools/TemplateTfmSwitchGenerator/Program.cs, tools/TemplateTfmSwitchGenerator/TemplateSwitchCase.cs, tools/TemplateTfmSwitchGenerator/TemplateTfmSwitchGenerator.csproj
- closes #654
Target Frameworks are each provided on a new line
Target Frameworks are each provided on a single line. This additionally adds a CLI tool that we can use to add additional Target Frameworks for instance if we wanted to bring back Tizen support in the future, as well as the ability to add/modify the supported TFMs such as when .NET 10 is introduced next year. This will quickly regenerate the TFM conditions making this easier to maintain over time.
=> Single Line TFMs for Single Project

src/Uno.Templates/content/unoapp/.template.config/template.json
Removing the "Design System Package" term for Uno DSP.
Related issue: https://github.com/unoplatform/private/issues/442
=> chore: Remove the "Design System Package" term for Uno DSP

build/.azure-pipelines.TemplateValidation.yml, build/.azure-pipelines.yml, build/templates/package-validation.yml, src/Directory.Build.targets, src/Uno.Templates/content/unoapp/Directory.Build.props
=> chore: Add markup+dsp validation

src/Uno.Templates/content/unoapp/.vsconfig
This workload is not needed to build wasm apps.
=> fix: Don't include the azure workload suggestion

tools/Uno.Sdk.Updater/Program.cs, tools/Uno.Sdk.Updater/Services/NuGetClient.cs
- fixes #764
- Bugfix
- Project automation
The Updater is always using the Private Feed to lookup available packages
The Updater will only use the Private Feed to lookup available packages if the UnoVersion has not been set or the UnoVersion is for a Stable branch.
This ensures that the latest available version selected in dev is always publicly available.
=> Private feed Fix

.vscode/settings.json, src/Uno.Templates/content/unoapp/.vscode/settings.json
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.templates/issues/767, closes https://github.com/unoplatform/uno.templates/pull/768
=> fix: Use jsonc for global.json in vscode

src/Uno.Templates/content/unoapp/.vsconfig, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.sln
The Windows SDK is not used when building apps, it's only needed when packaging an app for the store.
Related to https://github.com/unoplatform/uno/issues/17265.
=> fix: Remove unused vsconfig dependencies

build/.azure-pipelines.TemplateValidation.yml, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/global.json
This will prevent getting started issues when having .NET 9 installed.
=> fix: Don't allow prerelease by default

src/Uno.Templates/content/unoapp/MyExtensionsApp.1.sln
GitHub Issue (If applicable):
#776
- Code style update (formatting)
File is hidden from editor.
Allow Visual Studio to edit the file with its editor.
=> Sort and add .editorconfig to MyExtensionsApp.1.sln

tools/Uno.Sdk.Updater/Program.cs, tools/Uno.Sdk.Updater/Services/NuGetClient.cs, tools/Uno.Sdk.Updater/Utils/LocalFileSystem.cs, tools/Uno.Sdk.Updater/Utils/PackageValidationRecord.cs
- n/a
- Feature
- Project automation
When updating for a stable branch, the Updater will always pick the latest dependencies. 
When updating for a stable branch, the Updater will now validate that the available versions are compatible with the version of Uno.WinUI that we are packing for.
=> Sdk Updater - Uno Version Validation

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MainPage.xaml
- closes #835
C# Markup and XAML Blank Page use slightly different strings
C# Markup and XAML Blank Page now both use `Hello Uno Platform!`
=> Sync Hello Uno Platform string

src/Uno.Templates/content/unoapp/.template.config/template.json, tools/TemplateTfmSwitchGenerator/Program.cs
- related unoplatform/private#485
- Bugfix
net8.0/net9.0 is always placed first in the TFMs if it is used.
net8.0/net9.0 is always placed last in the TFMs if it is used.
=> Place netX.0 last

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.xaml
- closes #852
- Bugfix
The 'Add Resources Here' note is in the wrong location outside of the Resource Dictionary.
The comment has been moved to the correct location.
=> Fixing location of Add Resources note

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Package.appxmanifest
- closes #876
- Bugfix
When trying to open the Package.appxmanifest in the Visual Editor in Visual Studio it fails to load due to missing elements.
We now have placeholder elements that keep Visual Studio happy with what is actually required while still allowing Uno.Resizetizer to properly provide these values from the MSBuild properties that are part of Single Project.
=> Visual Studio fails to load the AppxManifest

tools/Uno.Sdk.Updater/Program.cs, tools/Uno.Sdk.Updater/ReadMe.md, tools/Uno.Sdk.Updater/Services/NuGetClient.cs
- fixes #880 
- Bugfix
- Project automation
The updater will always get the latest stable version while updating
The updater will force updates to be patches/service releases in the same Major.Minor release channel from when the stable release was made. The latest release will be picked for main branch/dev builds.
=> limit updates for stable to the current Major.Minor

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.xaml
- closes #726
- Bugfix
When selecting Toolkit and using the Fluent theme a reference to the Material Toolkit is added in the App.xaml
This is corrected so that no xmlns is added when using the Fluent theme... because apparently `&&` doesn't mean the same thing to dotnet templates 🤷‍♂️
=> Invalid reference to Material Toolkit

tools/Uno.Sdk.Updater/Program.cs
- Addresses automated update in #887
- Bugfix
Maui packages are always updated
Maui packages are only updated in Dev to avoid AndroidX misalignment in Release branches.
=> Skip Maui update on Release branch

tools/Uno.Sdk.Updater/Program.cs
- n/a
- Other... Prism is stable
Updater will only use preview version of Prism
Updater will use stable version of Prism
=> Allow Prism stable updates

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/.vsconfig
- fixes #760
The VS Component is hard coded and may not be the correct value in the future based on the selected TFM
We now can control this component based on which TFM is selected.
=> Make Android Component dynamic based on selected TFM

src/Uno.Templates/content/unoapp/.template.config/dotnetcli.host.json
- n/a
- Bugfix
there are 3 template properties that are not defined in the CLI configuration which causes one hidden flag to show up and 2 other properties to use the auto assigned values which aren't desirable.
We now define these 3 properties so that the Bootstrap Version is hidden from the CLI and we have a better flag for Lottie and SVG.
=> Adding missing template parameters

src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginPage.xaml.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainPage.xaml.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/SecondPage.xaml.cs
- n/a
We have logic to set the ViewModel name for C# Markup that is different depending on whether you are using MVUX or MVVM
With the recent changes to the MVUX generator we now have consistent naming across MVUX and MVVM therefore the unnecessary logic in the template.json is being removed
=> Cleaning up unnecessary bloat

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginPage.xaml.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainPage.xaml.cs, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/SecondPage.xaml.cs
GitHub Issue (If applicable): closes #934 
- Bugfix
C# Markup Recommended Template uses .All for SafeArea
C# Markup Recommended Template uses .VisibleBounds for SafeArea
=> fix: C# Markup Recommended Template uses .All Instead of .VisibleBounds for SafeArea

src/Uno.Templates/content/unoapp/.editorconfig
Using 2 spaces
Using 4 to match the default spacing for XML formats in Visual Studio
=> chore: Default spacing to 4 spaces for XML-based files

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Properties/PublishProfiles/win-AnyCPU.pubxml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18212
- Bugfix
Add an AnyCPU pub file, which does not contain a runtime identifier.
=> fix: Add AnyCPU publish file for winui

src/Uno.Sdk/ReadMe.md, src/Uno.Sdk/packages.json, src/Uno.Templates/content/unoapp/.run/MyExtensionsApp.1.run.xml, src/Uno.Templates/content/unoapp/.template.config/template.json, src/Uno.Templates/content/unoapp/MyExtensionsApp.1.MauiControls/MyExtensionsApp.1.MauiControls.csproj, src/Uno.Templates/content/unolib/CrossTargetedLibrary.csproj, tools/TemplateTfmSwitchGenerator/Program.cs, tools/Uno.Sdk.Updater/Program.cs
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno/issues/18840
- Bugfix
The latest version of Build Tools is unsupported by Microsoft Store and block users from publishing their apps
Downgraded until support is added
=> fix: Downgrade to 10.0.22621 for Build Tools compatibility

src/Uno.Templates/content/unoapp/.template.config/template.json, tools/TemplateTfmSwitchGenerator/Program.cs
Reverts unoplatform/uno.templates#1185
Placing desktop first breaks the WinAppSDK debugging.
=> Revert "fix(vs): Adjust tfm order for vs17.12 (backport #1184)"

src/Uno.Templates/content/unoapp/.template.config/template.json, tools/TemplateTfmSwitchGenerator/Program.cs
Reverts unoplatform/uno.templates#1184
Placing desktop first breaks the WinAppSDK debugging.
=> Revert "fix(vs): Adjust tfm order for vs17.12"

src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Mobile/Android/environment.conf, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/Android/environment.conf
Follows the recommendation from https://github.com/dotnet/runtime/issues/106410#issuecomment-2291508507
=> fix: Use "new" android bridge by default

src/Uno.Templates/content/unoapp/.vscode/launch.json
- Feature
Currently, only **Google Chrome** is available in `launch.json` for VS Code.
Added support for **Microsoft Edge (Chromium-based)** in `launch.json`, as it is also supported by VS Code.
(Reference: https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md)
=> feat(vscode): Add Edge debugging config to launch.json for Uno template

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MainPage.xaml, src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainPage.xaml
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno-private/issues/919
- Bugfix
The page's `ScrollViewer` is not a tab stop, which means tapping on blank area of the screen won't unfocus input fields
Fixed
=> fix: Make ScrollViewer a tab stop

src/Uno.Sdk/ReadMe.md, src/Uno.Sdk/packages.json
This updates Uno.Sdk to the latest available version. Addressing previously missed latest versions for:
- Uno.UI.HotDesign
- Uno.Toolkit
=> chore: Uno.Sdk Update - release/stable/5.6

.github/workflows/uno-updater.yml, version.json
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/6.0, based on #1376
=> Version bump after 6.0 release branch

.github/workflows/ci.yml
The `test-validation` job succeeds even if one or more matrix test jobs fail. This can result in PRs being auto-merged despite test failures.
The `test-validation` job will now correctly fail if any matrix test jobs fail. This ensures auto-merging is blocked when test failures occur.
=> chore: Update ci.yml to adjust Tests Validation

.github/workflows/uno-updater.yml, version.json
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/6.1, based on #1628
=> Version bump after 6.1 release branch

src/Uno.Templates/content/unoapp/global.json
GitHub Issue (If applicable): https://github.com/unoplatform/uno.templates/issues/1632
- Code style update (formatting)
opening the global.json file resulted in editorconfig caused adding of the missing space or the suggestion to do this, as a json file does normally have there a space character.
If I as user who got this annoying issue, did manually add this or my IDE did add this automatically, this were causing uno.check to fail with the error you can inspect in the linked issue
Added the missing character, which is automatically added if the local IDE Settings in VS 2022 e.g. are set to auto-fix those styling issues.
> [!IMPORTANT]
> Adding this character does cause uno-check to …
=> fix(globaljson): missing space character at global.json file caused the file to be filed for refactoring from the very beginning after app creation

.github/actions/ci/run-tests/action.yml
The GitHub Ubuntu runner-images already include the microsoft-packages.deb by default
=> ci: remove explicit packages-microsoft-prod.deb

version.json
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/6.2, based on #1699
=> Version bump after 6.2 release branch

.github/actions/sdk-update/action.yml, .github/sdk-update-exclude.json, tools/Uno.Sdk.Updater/Config/ExcludeConfig.cs, tools/Uno.Sdk.Updater/Program.cs, tools/Uno.Sdk.Updater/ReadMe.md, tools/Uno.Sdk.Updater/Utils/Cli.cs
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno/issues/21372
- Feature
- Improvement
The Uno.Sdk.Updater tool and CI workflow:
- Update all package groups unconditionally.  
- Merge manifests in a way that can cause unwanted downgrades.  
- Preserve local `VersionOverride` entries inconsistently, sometimes removing them.
- ReaMe.md still mentions .NET 9 for the override note
- Added support for excluding package groups from automatic updates using a JSON configuration file (`.github/sdk-update-exclude.json`) passed via a new CLI argument (`--exclude-file`).
- Adjusted merge logic to prevent **downgrades of local versions**.  
- Ensured local `VersionOverride` entries are always preserved and take precedence.  
- Added …
=> feat(Uno.Sdk.Updater): Add CLI exclude-file support and improve manifest merge logic
