src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainPage.xaml

GitHub Issue (If applicable): closes #33 

fix: Remove not_skia condition in XAML

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj

fix: Root namespace is wrong on Windows

---

build/.azure-pipelines.TemplateValidation.yml
src/Uno.Templates/Uno.Templates.csproj
src/Uno.Templates/content/unoapp/.template.config/dotnetcli.host.json
src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Tests/AppInfoTests.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.recommended.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Business/Models/AppConfig.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/GlobalUsings.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginPage.xaml.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginViewModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainPage.xaml.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainViewModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/SecondPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/ShellModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/ShellViewModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Caching/IWeatherCache.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Caching/WeatherCache.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Endpoints/IApiClient.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/appsettings.development.json
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/appsettings.json

GitHub Issue (If applicable): closes #47 
- Feature
No support for authentication in template
Adds authentication symbol with values none and custom

feat: Adding authentication with options None and Custom

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Wasm/WasmCSS/Fonts.css

The use of system-ui font is not recommended as it may be language specific - see https://infinnie.github.io/blog/2017/systemui.html
GitHub Issue (If applicable): closes #67
- Bugfix

fix: Avoid using system-ui font

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.recommended.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/AppResources.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Business/Models/AppConfig.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Business/Models/Entity.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Infrastructure/DebugHandler.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginPage.xaml.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginViewModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainPage.xaml.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainViewModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/SecondModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/SecondPage.xaml.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/SecondViewModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/Shell.xaml.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/ShellModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/ShellViewModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Caching/IWeatherCache.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Caching/WeatherCache.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Endpoints/IApiClient.cs

- Bugfix
Properties/Fields/Methods in wrong order
Correct order

fix: Reordering properties, methods etc

---

build/.azure-pipelines.TemplateValidation.yml
src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/Shell.xaml.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Styles/ColorPaletteOverride.cs

GitHub Issue (If applicable): closes #27
- Other: Re-enable C# Markup
C# Markup is disabled in the template
C# Markup is enabled in the template

Re-enable C# Markup

---

src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/Directory.Packages.props
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Gtk/MyExtensionsApp.1.Skia.Gtk.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Linux.FrameBuffer/MyExtensionsApp.1.Skia.Linux.FrameBuffer.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.WPF/MyExtensionsApp.1.Skia.WPF.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/AppResources.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/GlobalUsings.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj

fix: Uno.Extensions.Toolkit isn't included when toolkit is true

---

src/Uno.Templates/Uno.Templates.csproj
src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/Android/MainActivity.Android.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/Android/WebAuthenticationBrokerActivity.Android.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/MacCatalyst/Info.plist
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/iOS/Info.plist
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/macOS/Info.plist
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Server/Program.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Windows/Package.appxmanifest
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.recommended.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginPage.xaml.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginViewModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/appsettings.development.json
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/appsettings.json
src/Uno.Templates/reinstall.ps1

GitHub Issue (If applicable): closes #49
- Feature
Adds web auth

feat: Adding web auth

---

build/.azure-pipelines.TemplateValidation.yml
src/Uno.Templates/content/unoapp/.template.config/template.json

n/a
- Refactoring
CPM is disabled by default
CPM is enabled by default

chore: change CPM default to true

---

src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/Package.appxmanifest
src/Uno.Templates/reinstall.ps1

n/a
- Refactoring
appxmanifest doesn't understand `<!--#if`
appxmanifest understands `<!--#if`

chore: normalize conditional expression in appxmanifest

---

src/Directory.Build.targets
src/Directory.UnoMetadata.targets
src/Uno.Templates/Uno.Templates.csproj

- Feature
Package meta data in csproj
Meta data (including icon downloader) in targets file

feat: Adding metadata targets file

---

build/.azure-pipelines.TemplateValidation.yml
src/Uno.Templates/content/unoapp/.template.config/template.json

Disable csharp markup option

---

src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/Directory.Packages.props
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Tests/MyExtensionsApp._1.Tests.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.UITests/MyExtensionsApp._1.UITests.csproj

- preparing the template for work on #8
- Other
There is no option for CI
We have an option for CI with only the option for None available. This gives us a starting point to start working on CI PRs for both Azure Pipelines and GitHub Actions.

Adding CI option

---

src/Uno.Templates/Uno.Templates.csproj
src/Uno.Templates/content/unoapp/Directory.Packages.props
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/Android/Resources/values/Styles.xml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj
src/Uno.Templates/reinstall.ps1

- Bugfix
Android uses AppCompat base style
Android uses MaterialComponent base style

fix: Changing Android base style 

---

src/Uno.Templates/Uno.Templates.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Gtk/Program.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.WPF/Wpf/App.xaml.cs
src/Uno.Templates/reinstall.ps1

chore(deps): Update Uno packages

---

src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/MyExtensionsApp._1.Windows.csproj

GitHub Issue (If applicable): closes #187 
- Feature
Debugging Windows unpackaged required developer to change properties
Developer can switch between packaged and unpackaged in VS

chore: Adjust Windows guidance

---

src/Uno.Templates/content/unoapp/.template.config/template.json

GitHub Issue (If applicable): 
n/a
- Dependencies
Net 7 targets package with known security vulnerability. Net 8 targets preview 3
Packages updated

Update Microsoft packages

---

src/Uno.Templates/Uno.Templates.csproj
src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/AzurePipelines/jobs/smoke-test.yml
src/Uno.Templates/content/unoapp/AzurePipelines/jobs/unit-test.yml
src/Uno.Templates/content/unoapp/AzurePipelines/steps/install-dependencies.yml
src/Uno.Templates/content/unoapp/GitHub/steps/install_dependencies/action.yml
src/Uno.Templates/content/unoapp/azure-pipelines.yml

GitHub Issue (If applicable): closes #8
- Feature
Only GitHub Actions is supported
You can now get a basic Azure Pipelines build

Support Azure DevOps CI

---

src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.recommended.cs
src/Uno.Templates/content/unoapp/solution-config.props.sample

- n/a
- Refactoring
Whitespace uses mix of spaces and tabs. The default version of windows 10 in the overrides does not match the version of Windows 10 that we are targeting
Whitespaces & indents have been normalized, and the overrides file targets the correct version of Windows 10.

Normalizing whitespace & indents

---

src/Uno.Templates/Uno.Templates.csproj

Moving skiasharp to stable release version

chore(deps): Update skiasharp dependency

---

src/Uno.Templates/Uno.Templates.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.blank.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.recommended.cs
src/Uno.Templates/reinstall.ps1

- Feature
Updated to latest maui embedding

feat: Updating to latest maui extensions

---

src/Uno.Templates/content/unoapp/.template.config/template.json

- Documentation content changes
Refer to feature as .NET MAUI Embedding

chore: Fix .NET Maui naming

---

build/.azure-pipelines.TemplateValidation.yml
build/templates/canary-updater.yml
build/templates/dotnet-install-windows.yml
build/templates/package-validation.yml
src/Uno.Templates/Uno.Templates.csproj
src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/Directory.Build.props
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
src/Uno.Templates/reinstall.ps1

- Increments Extensions version
- Adds back the .NET MAUI Validation steps

feat: version bump and enabling maui validation

---

build/templates/package-validation.yml
src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/Directory.Build.props
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Mobile/MyExtensionsApp._1.Mobile.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/MyExtensionsApp._1.Windows.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/Properties/PublishProfiles/win-arm64.pubxml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/Properties/PublishProfiles/win-x64.pubxml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Windows/Properties/PublishProfiles/win-x86.pubxml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.blank.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/App.recommended.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/GlobalUsings.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MainPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/MainPage.xaml

- Feature
When selecting maui (-maui) platforms that don't support maui are removed
When selecting maui platform selection isn't modified
Maui embedding is selectively included based on tfm

feat: Enabling all platforms when selecting maui

---

src/Uno.Templates/Uno.Templates.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Skia.Linux.FrameBuffer/Program.cs
src/Uno.Templates/reinstall.ps1

chore: Adjust templates for FrameBufferHost breaking change

---

src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MainPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/LoginPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/MainPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/SecondPage.xaml

GitHub Issue (If applicable): closes #317 
- Bugfix
Maui namespaces included
Maui namespaces are only included if maui is selected and non-maui platforms are included
Also, added toolkit, material and navigation namespaces when these features are selected

fix: Adjusting namespaces for feature selction

---

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/AppHead.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MainPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/LoginPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/MainPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/SecondPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Styles/MaterialFontsOverride.xaml

- closes #263
- Bugfix
Files encoded UTF-8
Files encoded UTF-8 with BOM

Re-encode UTF-8 with BOM

---

src/Uno.Templates/content/unoapp/MyExtensionsApp._1/appsettings.development.json
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/appsettings.json

GitHub Issue (If applicable): fixes #332
- Bugfix
Oidc settings has wrong section name
Corrected section name to align with the name used in host builder

fix: Correcting settings section name

---

build/templates/dotnet-install-windows.yml
build/templates/install-windows-sdk.yml
build/templates/package-validation.yml

ci: Avoid unneeded install-windows-sdk step

---

src/Uno.Templates/content/unoapp/.template.config/template.json

- Documentation content changes

chore: Updating dsp title and description

---

build/.azure-pipelines.TemplateValidation.yml
build/templates/dotnet-install-windows.yml
build/templates/package-validation.yml
src/Uno.Templates/content/unoapp/.template.config/dotnetcli.host.json
src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/Directory.Packages.props
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj

- Feature
Have to manually add reference to uno.extensions.core.winui
REference to uno.extensions.core.winui is already added to the project

feat: Adding themeService

---

src/Uno.Templates/Uno.Templates.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Styles/MaterialFontsOverride.cs
src/Uno.Templates/reinstall.ps1

GitHub Issue (If applicable): closes #352 
- Bugfix
Correct path in overrides file

fix: Correct font path

---

src/Uno.Templates/content/unoapp/.template.config/template.json

- Documentation content changes
Better descriptions of options for CI

chore: Updating description

---

src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MainPage.xaml
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/MainPage.xaml

Tidying up the fix for maui namespaces

chore: Backport fix and tidyup

---

src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Server/MyExtensionsApp._1.Server.csproj

- fixes Ambiguous Reference caused by Implicit Namespaces
- Bugfix

Ambiguous reference with CSharpMarkup

---

src/Uno.Templates/content/unoapp/Directory.Build.props

GitHub Issue (If applicable): related to https://github.com/unoplatform/uno.templates/issues/376

fix: Add workaround for ENC0003 and Assembly Info unstable generation

---

build/.azure-pipelines.TemplateValidation.yml

GitHub Issue (If applicable): closes #396 
Add validation to ensure fix doesn't break again

chore: Validation for fix

---

src/Uno.Templates/content/unoapp/.template.config/template.json

- closes #389 
- closes #387 
Some symbols are missing descriptions
Added missing descriptions

Audit Template.json for missing Descriptions

---

build/.azure-pipelines.TemplateValidation.yml
src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/Presentation/LoginPage.xaml.cs

GitHub Issue (If applicable): closes #414
- Bugfix
DataContext incorrectly set on login page
DataContext correctly set on login page

fix: Correcting login datacontext

---

src/Uno.Templates/content/unoapp/GitHub/steps/install_dependencies/action.yml

GitHub Issue (If applicable): closes #435

feat: Bump setup-dotnet

---

src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/MyExtensionsApp._1/appsettings.development.json

Minor fixes for issues encountered during .NET Conf session
- Loginpage.xaml.cs doesn't get renamed to LoginPage.cs when using c# markup
- url in appsettings has wrong port

fix: Renaming login and fixing url

---

src/Uno.Templates/Uno.Templates.csproj
src/Uno.Templates/content/unoapp/.template.config/dotnetcli.host.json
src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/Directory.Packages.props
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.blank.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.recommended.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj
src/Uno.Templates/content/unoapp/nuget.config
src/Uno.Templates/reinstall.ps1

- Feature
Updates to latest Uno dev release
Updates to latest WinAppSdk + BuildTools
Adds Developer mode for overriding some behaviour
Tokens added:
```
$$EnableDeveloperMode_NuGet_Feed$$
$$EnableDeveloperMode_CPM_PackageReference$$
$$EnableDeveloperMode_PackageReference$$
$$EnableDeveloperMode_CPM_PackageVersion$$
$$EnableDeveloperMode_Frame_MainWindowContent$$
$$EnableDeveloperMode_Region_Navigate$$
```

feat: Adds developer mode

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Caching/WeatherCache.cs

- n/a
We don't fully utilize the CancellationToken and throw a Generic Exception
We now pass the CancellationToken into the methods that should make use of it. We throw a WebException to more correctly show we are offline.

Refactoring cancellation token use & exception handling

---

build/.azure-pipelines.TemplateValidation.yml
src/Uno.Templates/content/unoapp/.template.config/template.json

GitHub Issue (If applicable): closes #477

draft - issue 477

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginPage.xaml

GitHub Issue (If applicable): closes #481
https://github.com/unoplatform/uno.templates/issues/481
- Bugfix
- Code style update (formatting)
- The password box doesn't bind Password property
- Binding doesn't update properties
https://github.com/unoplatform/uno.templates/issues/481
- Bind Password property
- Update Username and Password properties properly
- [ x ] Associated with an issue (GitHub or internal)
Internal Issue (If applicable): https://github.com/unoplatform/uno.templates/issues/481

Fixing custom login data binding

---

src/Uno.Templates/content/unoapp-uwp/.vscode/extensions.json

Adapt VS Code extension recommendation to the new default.
Same as #492 but for UWP
UWP templates don't offer the same recommendations as WinUI templates
Both sets of templates offer the same recommendation

chore: remove unwanted recommendation (for uwp)

---

build/.azure-pipelines.TemplateValidation.yml
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/LoginPage.xaml.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/MainPage.xaml.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/SecondPage.xaml.cs

GitHub Issue (If applicable): fixes #500
- Bugfix
Fixes compile error by including missing comma
- [ X ] Associated with an issue (GitHub or internal)

fix: Correcting invalid markup when toolkit not included

---

build/.azure-pipelines.TemplateValidation.yml

- closes #507
Issue #505 is not currently tested as part of the Test Validation cases
Adding test validation for C# Markup with each of the Auth Providers for both MVVM and MVUX

Adding validation test cases for #505

---

src/Uno.Templates/content/unoapp/Directory.Packages.props
src/Uno.Templates/content/unoapp/global.json

Add notes on updating the Uno Version

---

src/Uno.Templates/content/unoapp/.template.config/template.json

- n/a
- Feature
We just target .net8
We now allow for the creation of a project with .net9

Adding support for .net9

---

src/Uno.Templates/Uno.Templates.csproj

- n/a
- Other... Please describe: dependencies

Update winappsdk version

---

build/.azure-pipelines.yml
build/templates/package-validation.yml
build/templates/template-validation.yml
src/Uno.Templates/Uno.Templates.csproj

- n/a
Update DSP package. This should help avoid the deadlock that is causing builds to fail randomly

chore: update DSP dependency

---

src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/Directory.Packages.props
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Gtk/MyExtensionsApp.1.Skia.Gtk.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.Linux.FrameBuffer/MyExtensionsApp.1.Skia.Linux.FrameBuffer.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Skia.WPF/MyExtensionsApp.1.Skia.WPF.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj

- fixes #462
- Bugfix
We do not actually have the SkiaSharp packages defined as top level packages
We now add the SkiaSharp packages as top level packages

Adding SkiaSharp packages

---

src/Uno.Templates/content/unoapp/.vscode/launch.json
src/Uno.Templates/content/unoapp/.vscode/tasks.json
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Properties/launchsettings.json

Use proper replacement variable for launch settings in WSL

chore: Adjust WSL launch settings

---

build/.azure-pipelines.TemplateValidation.yml
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Server/MyExtensionsApp.1.Server.csproj

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.templates/issues/602
- Bugfix
Adjust for server build.

fix: Restore server validations

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj

See https://github.com/unoplatform/uno/pull/16097

fix: Move desktop back to not be first

---

build/.azure-pipelines.TemplateValidation.yml
src/Directory.Build.targets
src/Uno.Templates/content/unoapp/Directory.Packages.props
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.MauiControls/MyExtensionsApp.1.MauiControls.csproj
src/Uno.Templates/content/unomauilib/Directory.Packages.props

re-enable disabled tests

---

src/Uno.Templates/content/unoapp/.template.config/template.json

chore: shorten desktop description for the Wizard

---

src/Directory.Build.targets

- related unoplatform/uno#16152
- related unoplatform/uno-private#428
- related unoplatform/uno-private#429
- Other... Please describe: updates Uno for SDK fixes

chore: bump uno for SDK fixes

---

src/Uno.Templates/content/unolib/CrossTargetedLibrary.csproj

feat: adding commented block for UnoFeatures in Library template

---

src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Mobile/UnoQuickStart.Mobile.csproj
src/Uno.Templates/content/unoapp-uwp/UnoQuickStart.Mobile/iOS/PrivacyInfo.xcprivacy
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/iOS/PrivacyInfo.xcprivacy

Related to https://github.com/unoplatform/uno/pull/16445, closes https://github.com/unoplatform/uno.templates/issues/639

fix: Add Apple Privacy manifest

---

src/Uno.Templates/content/unoapp/Directory.Build.props

- Other: Adding a comment pointing to the documentation
Update Directory.Build.props to add more details regarding the implicit packages

chore: Update Directory.Build.props to add more details regarding the implicit packages

---

src/Uno.Templates/content/unoapp/.template.config/template.json

GitHub Issue (If applicable): https://github.com/unoplatform/private/issues/443
Updated DSP to Uno DSP theme file

docs: updated DSP theme file

---

src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj

- fixes #683
- Bugfix
Lottie only brought in when the Lottie feature is selected in the template
Lottie feature is now added if you choose Fluent or Lottie.

ensure we add Lottie

---

build/.azure-pipelines.yml
build/gitversion.yml

Moves offset to gitversion configuration for main branch

ci: move offset to CD configuration for main branch

---

build/.azure-pipelines.yml

ci: Adjust variable override casing

---

build/.azure-pipelines.yml
build/templates/package-validation.yml

ci: Restore macos template validation

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.recommended.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/ShellModel.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Presentation/ShellViewModel.cs

GitHub Issue (If applicable): closes #701
- Feature
Navigate is called from ShellViewModel/Model
IsDefault is set on the Main route
- [ X ] Associated with an issue (GitHub or internal)

chore: simplify initial navigation

---

src/Uno.Templates/content/unoapp/.vsconfig

GitHub Issue (If applicable): 
- Feature
No prompt
Prompting, based on https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#missingcomponentdetectionandnotification

feat: Prompt users to install Uno Platform extension in Visual Studio

---

src/Uno.Templates/content/unoapp/.vscode/launch.json

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.templates/issues/745

fix: Align vscode launch.json profiles

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj

Reverts unoplatform/uno.templates#827

Revert "chore: Enable open-sans by default"

---

tools/Uno.Sdk.Updater/Program.cs

Fixes core packages not getting updated

fix: Upgrade core packages

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/Android/Assets/AboutAssets.txt

fix: Fix typo in AboutAssets.txt

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/Windows/Properties/PublishProfiles/win-arm64.pubxml
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/Windows/Properties/PublishProfiles/win-x64.pubxml
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/Windows/Properties/PublishProfiles/win-x86.pubxml

- Feature
Not enabled.
The underlying issue https://github.com/microsoft/CsWinRT/issues/373 is fixed, can be enabled now.

feat: Enable `PublishTrimmed` in Windows publish profiles

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MainPage.xaml

GitHub Issue (If applicable): closes #Internal
- Bugfix
No root element - StackPanel in center of screen
Grid at root

chore: Insert grid at root

---

build/.azure-pipelines.TemplateValidation.yml
build/.azure-pipelines.yml
build/templates/package-validation.yml
src/Uno.Sdk/ReadMe.md
src/Uno.Sdk/packages.json

- Bump dotnet for winui 1.6, including 8.0.40x missing update
- Bump to Xcode 15.4
- Bootstrapper net9.0 compatibility

ci: Bump to latest uno.check

---

src/Uno.Templates/content/unoapp/.template.config/TemplateWizard.json

GitHub Issue (If applicable): closes #991
- Bugfix
Configuration is not added as requirement for Http and Localization, but i should.
Configuration is added as requirement for Http and Localization.

fix: Add config as requirement for http and loc

---

src/Uno.Sdk/ReadMe.md
src/Uno.Sdk/packages.json
src/Uno.Templates/content/unoapp/.run/MyExtensionsApp.1.run.xml
src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.MauiControls/MyExtensionsApp.1.MauiControls.csproj
src/Uno.Templates/content/unolib/CrossTargetedLibrary.csproj
tools/TemplateTfmSwitchGenerator/Program.cs
tools/Uno.Sdk.Updater/Program.cs

GitHub Issue (If applicable): related to https://github.com/unoplatform/uno/issues/18840
- Bugfix
Build tools support was missing in Partner Center
Latest build tools support has been added to Partner Center

feat: Update to WinAppSDK 26100

---

src/Uno.Sdk/packages.json

closes https://github.com/unoplatform/uno.templates/issues/1144

fix: Fix bump default net9 maui

---

build/templates/package-validation.yml

Avoids hitting disk space issues

ci: Remove unused dependencies

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/Android/Main.Android.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/WebAssembly/Program.cs

fix: Initialize logging on WASM for blank template

---

src/Directory.Build.targets
src/Uno.Sdk/Uno.Sdk.csproj

closes https://github.com/unoplatform/uno.hotdesign/issues/3274

fix: Adjust sdk version number variable

---

src/Uno.Sdk/packages.json

chore: Updating HotDesign to 1.8

---

src/Uno.Templates/content/unoapp/.template.config/template.json

GitHub Issue (If applicable): closes #1339

chore: Update desktop description

---

src/Uno.Sdk/ReadMe.md
src/Uno.Sdk/packages.json

Uno.Sdk Update - main

---

.github/actions/ci/run-tests/action.yml
src/Uno.Templates/content/unoapp/.template.config/TemplateWizard.json
src/Uno.Templates/content/unoapp/.template.config/template.json

chore: adjust options for breaking changes

---

.github/actions/ci/generate-test-matrix/action.yml
src/Uno.Templates/content/unoapp/.template.config/template.json
src/Uno.Templates/content/unolib-uitest/.template.config/template.json
src/Uno.Templates/content/unolib/.template.config/template.json
src/Uno.Templates/content/unomauilib/.template.config/template.json
tools/TemplateTfmSwitchGenerator/Program.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1137

fix: Remove net8 support from the template

---

src/Uno.Sdk/ReadMe.md
src/Uno.Sdk/packages.json

Uno.Sdk Update - release/stable/6.0

---

src/Uno.Templates/content/unoapp/.template.config/TemplateWizard.json

GitHub Issue (If applicable): closes internal
- Feature
Internal Issue (If applicable): [Teams](https://teams.microsoft.com/l/message/19:c857d68e0be84cfba6ff9a8611200680@thread.tacv2/1744902774850?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=f55cdec8-036b-4efa-8e1a-c4129ba9bf12&parentMessageId=1744902774850&teamName=Uno%20Platform&channelName=Collab%20Lounge&createdTime=1744902774850)

chore: Restructure platform sections for clarity

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/GlobalUsings.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/757

fix: GlobalUsings warning

---

src/Uno.Templates/content/unoapp/.template.config/TemplateWizard.json
src/Uno.Templates/content/unoapp/.template.config/dotnetcli.host.json
src/Uno.Templates/content/unoapp/.template.config/template.json

- Bugfix
Adjust Templates/Wizard to match latest changes needed for 6.0 Release ([Related discussion](https://teams.microsoft.com/l/message/19:2f70f2e6c0a84549b5137ceda4b298a2@thread.tacv2/1746185633581?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=f55cdec8-036b-4efa-8e1a-c4129ba9bf12&parentMessageId=1746185633581&teamName=Uno%20Platform&channelName=RnD%20-%20Tooling%20-%20Templates%20and%20Wizard&createdTime=1746185633581))

fix: Adjust Templates/Wizard to match latest changes needed for 6.0 Release

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/Desktop/Program.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/20221

fix: use STAThread on Skia Desktop's main thread

---

.github/actions/ci/build-packages/action.yml
.github/actions/ci/generate-test-matrix/action.yml
.github/actions/ci/run-tests/action.yml
.github/actions/ci/sign-package/action.yml
.github/actions/ci/tag-release/action.yml
.github/workflows/ci.yml
src/Uno.Sdk.Updater.targets
src/Uno.Sdk/ReadMe.md
src/Uno.Sdk/packages.json

related to https://github.com/unoplatform/uno.templates/issues/1492

chore: Update validation to 9.0.300

---

.github/actions/ci/run-tests/action.yml
src/Uno.Templates/content/unoapp/MyExtensionsApp.1.MauiControls/MyExtensionsApp.1.MauiControls.csproj
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.recommended.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/Android/MainActivity.Android.cs

Fixes https://github.com/unoplatform/uno.templates/issues/619

chore: Enable TreatWarningsAsErrors

---

src/Uno.Sdk/ReadMe.md
src/Uno.Sdk/packages.json

chore: Updating HD

---

src/Uno.Templates/content/unoapp/.template.config/TemplateWizard.json

Just making this PR as the place for discussion regarding the wording and suggesting my version. We also may choose to put Navigation and Blank in the double quotes but i've decided not to do so since in other places we don't do that
Fixes #1566

chore: Update wording for architecture.none

---

src/Uno.Templates/content/unoapp/MyExtensionsApp.1/App.recommended.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Caching/IWeatherCache.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Services/Caching/WeatherCache.cs

fixes https://github.com/unoplatform/uno.rider/issues/297

chore: fix template code gen

---

.github/actions/ci/generate-test-matrix/action.yml
.github/actions/ci/run-tests/action.yml
src/Uno.Sdk/ReadMe.md
src/Uno.Sdk/packages.json
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/Desktop/Program.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/WebAssembly/Program.cs
src/Uno.Templates/content/unoapp/MyExtensionsApp.1/Platforms/iOS/Main.iOS.cs

related https://github.com/unoplatform/uno/issues/20765

chore: add skia runtime package ref for maui embedding

---

.github/actions/ci/generate-test-matrix/action.yml
src/Uno.Templates/content/unolib/.template.config/template.json
src/Uno.Templates/content/unolib/CrossTargetedLibrary.csproj

GitHub Issue (If applicable): closes #1614

chore: enable SkiaRenderer by default for unolib

---

src/Uno.Sdk/ReadMe.md
src/Uno.Sdk/packages.json

Uno.Sdk Update - release/stable/6.1

---

src/Uno.Templates/content/unoapp/.template.config/template.json

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17241
Media Element is confusing, as such a thing does not exist
Changed to **Media Player Element**

fix: Change display name for `MediaPlayerElement` feature

---

src/Uno.Sdk/ReadMe.md
src/Uno.Sdk/packages.json

Remove duplicate `Uno.WinUI.Svg` entry in the Core group of `packages.json` and `ReadMe.md`

chore: Remove duplicate Uno.WinUI.Svg entry in Core group of packages.json and ReadMe.md

---

src/Uno.Sdk/ReadMe.md
src/Uno.Sdk/packages.json

Uno.Sdk Update - release/stable/6.2

---

src/Uno.Sdk/ReadMe.md
src/Uno.Sdk/packages.json

Uno.Sdk Update - release/stable/6.3
